language: python
python:
  - "3.6"
script: 
    # Running pytest on the util functions 
    - python3 -m pytest tests/ 

# Installing the required libraries 
install: 
    # Required for pylint 
    - pip install pylint==1.8.2
    - pip3 install --extra-index-url $EXTRA_INDEX_URL --trusted-host $TRUSTED_HOST -r requirements.txt

after_success:
  - git config --global user.name $USERNAME
  - git config --global user.email $EMAIL
  - pip install python-semantic-release
  
  
